chore: refactor repo structure
aerogear/charmil pull request #188
Opened 2021-07-28 11:07 UTC by ankithans

Closes #180 
### Description
rm pkg, put pkg into core

2021-07-28 11:15 UTC, wtrocki commented
Before applying changes put comment what you planning to do to get validation. It saves time :D

2021-07-28 11:16 UTC, wtrocki commented
Changes make no sense for me. 

Scafolders are part of the CLI not core.

2021-07-28 11:18 UTC, ankithans commented
so we can move it to cmd folder(in the root). I followed pkg, just for the sake - we provide starter and we should follow it.

2021-07-28 11:19 UTC, wtrocki commented
We should have functional folders for each component. cmd/pkg/internal are not folders. they have specific meaning and should not be mixed together. 

That is classical project layout: https://github.com/golang-standards/project-layout

However it will not work for our use case as we keep multiple elements in the repo.

2021-07-28 11:23 UTC, wtrocki commented
Side note. Starter will be the only module that we will keep as we do not need it to be consumable as lib, but it will be used by init etc. Rest will be simply folders.

2021-07-28 11:41 UTC, ankithans commented
> Let's document repository structure

yes...

validator, starter, core - already a folder
cli - present in cmd/ folder. We don't need pkg folder and we can put comands and templates in cmd/ folder.

the above change will be fine?

2021-07-28 11:46 UTC, wtrocki commented
Please read: https://github.com/golang-standards/project-layout

cmd folder is special folder. Should not contain much code.

2021-07-28 11:48 UTC, ankithans commented
yeah sorry, code should not be used or imported into other projects, so need to put that into internal

2021-07-28 11:49 UTC, wtrocki commented
Agreed

2021-07-28 12:48 UTC, ankithans commented
> cli/pkg and cli/cmd?

yeah
```
cli
   cmd
   pkg
core
starter
validator
```
can we rename cli to charmil? (this can be ignored)

2021-07-28 13:05 UTC, namit-chandwani commented
>    pkg - here pkg or internal??

Internal would be better IMO, since the code in `cli/pkg` won't be of any use outside this repo

2021-07-29 09:27 UTC, ankithans commented
@wtrocki ready for review

2021-07-29 09:31 UTC, namit-chandwani requested changes

2021-07-29 09:31 UTC, namit-chandwani commented on CONTRIBUTING.md
>  You can run the CLI commands files directly with go run. All commands and subcommands are in the ./pkg/cmd folder.
Maybe you can change this too now

```suggestion
You can run the CLI commands files directly with go run. All commands and subcommands are in the ./cli/internal/cmd folder.
```

2021-07-29 09:31 UTC, wtrocki approved these changes

2021-07-29 09:32 UTC, merged